# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/insighthunter',
                'doc_host': 'https://riversdark.github.io',
                'git_url': 'https://github.com/riversdark/insighthunter',
                'lib_path': 'insighthunter'},
  'syms': {'insighthunter.core': {'insighthunter.core.foo': ('core.html#foo', 'insighthunter/core.py')}}}